import { applyMiddleware, createStore } from "redux";
import { composeWithDevTools } from "redux-devtools-extension";
import createSagaMiddleware from "redux-saga";
import { spawn } from "redux-saga/effects";
import watchRegisterSaga from "../../../Administration/Redux/Sagas/RegisterSaga";
import economicsMiddleware from "../../../Economics/Redux/Middleware/EconomicsMiddleware";
import watchFetchEconomicsTreeviewKeysSaga from "../../../Economics/Redux/Sagas/FetchEconomicsTreeviewKeysSaga";
import watchFetchHeatMapDataSaga from "../../../Economics/Redux/Sagas/FetchHeatMapDataSaga";
import watchFetchStoredEconomicsDataSaga from "../../../Economics/Redux/Sagas/FetchStoredEconomicsDataSaga";
import watchFetchStoredEconomicsResultsSaga from "../../../Economics/Redux/Sagas/FetchStoredEconomicsResultsSaga";
import watchFetchStoredEconomicsSensitivitiesSaga from "../../../Economics/Redux/Sagas/FetchStoredEconomicsSensitivitiesSaga";
import watchGetEconomicsPlotChartDataSaga from "../../../Economics/Redux/Sagas/GetEconomicsPlotChartDataSaga";
import watchGetEconomicsResultsByIdSaga from "../../../Economics/Redux/Sagas/GetEconomicsResultsByIdSaga";
import watchGetEconomicsSensitivitiesByIdSaga from "../../../Economics/Redux/Sagas/GetEconomicsSensitivitiesByIdSaga";
import watchRunEconomicsAnalysisSaga from "../../../Economics/Redux/Sagas/RunEconomicsAnalysisSaga";
import watchRunEconomicsForecastAggregationSaga from "../../../Economics/Redux/Sagas/RunEconomicsForecastAggregationSaga";
import watchSaveCostsRevenuesSaga from "../../../Economics/Redux/Sagas/SaveCostsRevenuesSaga";
import watchSaveEconomicsParametersSaga from "../../../Economics/Redux/Sagas/SaveEconomicsParametersSaga";
import watchSaveEconomicsResultsSaga from "../../../Economics/Redux/Sagas/SaveEconomicsResultsSaga";
import watchSaveEconomicsSensitivitiesSaga from "../../../Economics/Redux/Sagas/SaveEconomicsSensitivitiesSaga";
import watchTransformEconomicsChartDataSaga from "../../../Economics/Redux/Sagas/TransformEconomicsPlotChartsDataSaga";
import watchFetchForecastTreeviewKeysSaga from "../../../Forecast/Redux/Sagas/FetchForecastTreeviewKeysSaga";
import watchFetchStoredForecastingResultsSaga from "../../../Forecast/Redux/Sagas/FetchStoredForecastingResultsSaga";
import watchGetForecastQADataSaga from "../../../Forecast/Redux/Sagas/GetForecastQualityAssuranceDataSaga";
import watchGetForecastResultsChartDataSaga from "../../../Forecast/Redux/Sagas/GetForecastResultsChartDataSaga";
import watchGetSelectedForecastDataByIdSaga from "../../../Forecast/Redux/Sagas/GetSelectedForecastDataByIdSaga";
import watchPutSelectChartOptionSaga from "../../../Forecast/Redux/Sagas/PutSelectChartOptionSaga";
import watchTransformForecastChartDataSaga from "../../../Forecast/Redux/Sagas/TransformForecastChartDataSaga";
import watchConnectDatabaseSaga from "../../../Import/Redux/Sagas/ConnectDatabaseSaga";
import watchFetchApplicationHeadersSaga from "../../../Import/Redux/Sagas/FetchApplicationHeadersSaga";
import watchFetchStoredInputDeckSaga from "../../../Import/Redux/Sagas/FetchStoredInputDeckSaga";
import watchSaveInputDeckSaga from "../../../Import/Redux/Sagas/SaveInputDeckSaga";
import watchValidateForecastInputDeckSaga from "../../../Import/Redux/Sagas/ValidateForecastInputDeckSaga";
import watchAutogenerateNetworkSaga from "../../../Network/Redux/Sagas/AutogenerateNetworkSaga";
import watchDisplayNetworkBySelectionSaga from "../../../Network/Redux/Sagas/DisplayNetworkBySelectionSaga";
import watchFetchStoredDeclineCurveParametersSaga from "../../../Network/Redux/Sagas/FetchStoredDeclineCurveParametersSaga";
import watchFetchStoredForecastParametersSaga from "../../../Network/Redux/Sagas/FetchStoredForecastParametersSaga";
import watchFetchStoredNetworkDataSaga from "../../../Network/Redux/Sagas/FetchStoredNetworkDataSaga";
import watchFetchStoredProductionPrioritizationSaga from "../../../Network/Redux/Sagas/FetchStoredProductionPrioritizationSaga";
import watchGetDeclineParametersByIdSaga from "../../../Network/Redux/Sagas/GetDeclineParametersByIdSaga";
import watchGetProductionPrioritizationByIdSaga from "../../../Network/Redux/Sagas/GetProductionPrioritizationByIdSaga";
import watchRunForecastSaga from "../../../Network/Redux/Sagas/RunForecastSaga";
import watchSaveDeclineParametersSaga from "../../../Network/Redux/Sagas/SaveDeclineParametersSaga";
import watchSaveForecastParametersSaga from "../../../Network/Redux/Sagas/SaveForecastParametersSaga";
import watchSaveForecastSaga from "../../../Network/Redux/Sagas/SaveForecastSaga";
import watchSaveNetworkSaga from "../../../Network/Redux/Sagas/SaveNetworkSaga";
import watchSaveProductionPrioritizationSaga from "../../../Network/Redux/Sagas/SaveProductionPrioritizationSaga";
import watchUpdateForecastParametersSaga from "../../../Network/Redux/Sagas/UpdateForecastParametersSaga";
import watchCreateNewProjectSaga from "../../../Project/Redux/Sagas/CreateProjectSaga";
import watchFetchStoredProjectsSaga from "../../../Project/Redux/Sagas/FetchStoredProjectsSaga";
import watchOpenRecentProjectSaga from "../../../Project/Redux/Sagas/OpenRecentProjectSaga";
import watchFetchUnitSettingsSaga from "../../../Settings/Redux/Sagas/Sagas/UnitSettingsSaga";
import watchFetchStoredVisualyticsDataSaga from "../../../Visualytics/Redux/Sagas/FetchStoredVisualyticsDataSaga";
import watchFetchVisualyticsTreeviewKeysSaga from "../../../Visualytics/Redux/Sagas/FetchVisualyticsTreeviewKeysSaga";
import watchGetVisualyticsChartDataSaga from "../../../Visualytics/Redux/Sagas/GetVisualyticsChartDataSaga";
import watchSaveVisualyticsSaga from "../../../Visualytics/Redux/Sagas/SaveVisualyticsSaga";
import watchTransformVisualyticsChartDataSaga from "../../../Visualytics/Redux/Sagas/TransformVisualyticsDataSaga";
import rootReducer from "../Reducers/RootReducer";
import watchDeleteDataByIdSaga from "../Sagas/DeleteDataByIdSaga";
import watchFetchMatchObjectSaga from "../Sagas/FetchMatchObjectSaga";
import watchFetchUserDetailsSaga from "../Sagas/FetchUserDetailsSaga";
import watchGetTableDataByIdSaga from "../Sagas/GetTableDataByIdSaga";
import watchLoginSaga from "../Sagas/LoginSaga";
import watchUpdateDataByIdSaga from "../Sagas/UpdateDataByIdSaga";

//TODO Will need a registration mechanism for each module
function* rootSaga() {
  yield spawn(watchLoginSaga);
  yield spawn(watchRegisterSaga);
  yield spawn(watchConnectDatabaseSaga);
  yield spawn(watchCreateNewProjectSaga);
  yield spawn(watchFetchStoredProjectsSaga);
  yield spawn(watchFetchUnitSettingsSaga);
  yield spawn(watchOpenRecentProjectSaga);
  yield spawn(watchFetchStoredInputDeckSaga);
  yield spawn(watchSaveInputDeckSaga);
  yield spawn(watchAutogenerateNetworkSaga);
  yield spawn(watchRunForecastSaga);
  yield spawn(watchSaveForecastParametersSaga);
  yield spawn(watchUpdateForecastParametersSaga);
  yield spawn(watchSaveNetworkSaga);
  yield spawn(watchFetchApplicationHeadersSaga);
  yield spawn(watchFetchStoredNetworkDataSaga);
  yield spawn(watchFetchStoredForecastParametersSaga);
  yield spawn(watchDisplayNetworkBySelectionSaga);
  yield spawn(watchSaveForecastSaga);
  yield spawn(watchFetchUserDetailsSaga);
  yield spawn(watchFetchStoredForecastingResultsSaga);
  yield spawn(watchFetchForecastTreeviewKeysSaga);
  yield spawn(watchGetForecastResultsChartDataSaga);
  yield spawn(watchFetchMatchObjectSaga);
  yield spawn(watchGetSelectedForecastDataByIdSaga);
  yield spawn(watchSaveCostsRevenuesSaga);
  yield spawn(watchSaveEconomicsParametersSaga);
  yield spawn(watchFetchStoredEconomicsDataSaga);
  yield spawn(watchSaveEconomicsSensitivitiesSaga);
  yield spawn(watchFetchStoredEconomicsSensitivitiesSaga);
  yield spawn(watchGetEconomicsSensitivitiesByIdSaga);
  yield spawn(watchRunEconomicsAnalysisSaga);
  yield spawn(watchRunEconomicsForecastAggregationSaga);
  yield spawn(watchFetchHeatMapDataSaga);
  yield spawn(watchGetTableDataByIdSaga);
  yield spawn(watchFetchStoredProductionPrioritizationSaga);
  yield spawn(watchFetchStoredDeclineCurveParametersSaga);
  yield spawn(watchGetProductionPrioritizationByIdSaga);
  yield spawn(watchGetDeclineParametersByIdSaga);
  yield spawn(watchFetchStoredEconomicsResultsSaga);
  yield spawn(watchSaveEconomicsResultsSaga);
  yield spawn(watchGetEconomicsResultsByIdSaga);
  yield spawn(watchDeleteDataByIdSaga);
  yield spawn(watchSaveDeclineParametersSaga);
  yield spawn(watchSaveProductionPrioritizationSaga);
  yield spawn(watchFetchEconomicsTreeviewKeysSaga);
  yield spawn(watchGetForecastQADataSaga);
  yield spawn(watchTransformForecastChartDataSaga);
  yield spawn(watchPutSelectChartOptionSaga);
  yield spawn(watchSaveVisualyticsSaga);
  yield spawn(watchFetchVisualyticsTreeviewKeysSaga);
  yield spawn(watchFetchStoredVisualyticsDataSaga);
  yield spawn(watchUpdateDataByIdSaga);
  yield spawn(watchGetVisualyticsChartDataSaga);
  yield spawn(watchGetEconomicsPlotChartDataSaga);
  yield spawn(watchTransformVisualyticsChartDataSaga);
  yield spawn(watchTransformEconomicsChartDataSaga);
  yield spawn(watchValidateForecastInputDeckSaga);
}

const sagaMiddleware = createSagaMiddleware();

const store = createStore(
  rootReducer,
  composeWithDevTools(applyMiddleware(economicsMiddleware, sagaMiddleware))
);

sagaMiddleware.run(rootSaga);

export { store };
