export const variablesObj: Record<string, string> = {
  "Oil Rate": "oilrate",
  "Gas Rate": "gasRate",
  "Water Rate": "waterRate",
  "Liquid Rate": "liquidRate",
  "Base, Sediment & Water": "bSW",
  "Condensate/Gas Ratio": "cGR",
  "Water/Gas Ratio": "wGR",
  GOR: "gOR",
  "Cummulative Gas Produced": "cumGasProd",
  "Cummulative Oil Produced": "cumOilProd",
  "Cummulative Water Produced": "cumWaterProd",
  "Hydrocarbon Stream": "hyrocarbonStream",
  Cutback: "cutBack",
  "Cutback Ratio": "cutBackRatio",
  "Crude Oil Losses": "crudeOilLossess",
  Day: "day",
  Month: "month",
  Year: "year",
  "Decline Rate": "declineRate",
  "Gas Demand": "gasDemand",
  "Gas OwnUse": "gasOwnUse",
  "Gas Ultimate Recovery": "uRg",
  "Oil Ultimate Recovery": "uRo",
};
