export const dateFormatData = [
  "d/M/y",
  "d/M/ yo",
  "d/M/ yy",
  "d/M/ yyyy",
  "d/ Mo/y",
  "d/ Mo/ yo",
  "d/ Mo/ yy",
  "d/ Mo/ yyyy",
  "d/ MM/y",
  "d/ MM/ yo",
  "d/ MM/ yy",
  "d/ MM/ yyyy",
  "d/ MMM/y",
  "d/ MMM/ yo",
  "d/ MMM/ yy",
  "d/ MMM/ yyyy",
  " do/M/y",
  " do/M/ yo",
  " do/M/ yy",
  " do/M/ yyyy",
  " do/ Mo/y",
  " do/ Mo/ yo",
  " do/ Mo/ yy",
  " do/ Mo/ yyyy",
  " do/ MM/y",
  " do/ MM/ yo",
  " do/ MM/ yy",
  " do/ MM/ yyyy",
  " do/ MMM/y",
  " do/ MMM/ yo",
  " do/ MMM/ yy",
  " do/ MMM/ yyyy",
  " dd/M/y",
  " dd/M/ yo",
  " dd/M/ yy",
  " dd/M/ yyyy",
  " dd/ Mo/y",
  " dd/ Mo/ yo",
  " dd/ Mo/ yy",
  " dd/ Mo/ yyyy",
  " dd/ MM/y",
  " dd/ MM/ yo",
  " dd/ MM/ yy",
  " dd/ MM/ yyyy",
  " dd/ MMM/y",
  " dd/ MMM/ yo",
  " dd/ MMM/ yy",
  " dd/ MMM/ yyyy",
  " ddd/M/y",
  " ddd/M/ yo",
  " ddd/M/ yy",
  " ddd/M/ yyyy",
  " ddd/ Mo/y",
  " ddd/ Mo/ yo",
  " ddd/ Mo/ yy",
  " ddd/ Mo/ yyyy",
  " ddd/ MM/y",
  " ddd/ MM/ yo",
  " ddd/ MM/ yy",
  " ddd/ MM/ yyyy",
  " ddd/ MMM/y",
  " ddd/ MMM/ yo",
  " ddd/ MMM/ yy",
  " ddd/ MMM/ yyyy",
  "M/d/y",
  "M/d/ yo",
  "M/d/ yy",
  "M/d/ yyyy",
  "M/ do/y",
  "M/ do/ yo",
  "M/ do/ yy",
  "M/ do/ yyyy",
  "M/ dd/y",
  "M/ dd/ yo",
  "M/ dd/ yy",
  "M/ dd/ yyyy",
  "M/ ddd/y",
  "M/ ddd/ yo",
  "M/ ddd/ yy",
  "M/ ddd/ yyyy",
  " Mo/d/y",
  " Mo/d/ yo",
  " Mo/d/ yy",
  " Mo/d/ yyyy",
  " Mo/ do/y",
  " Mo/ do/ yo",
  " Mo/ do/ yy",
  " Mo/ do/ yyyy",
  " Mo/ dd/y",
  " Mo/ dd/ yo",
  " Mo/ dd/ yy",
  " Mo/ dd/ yyyy",
  " Mo/ ddd/y",
  " Mo/ ddd/ yo",
  " Mo/ ddd/ yy",
  " Mo/ ddd/ yyyy",
  " MM/d/y",
  " MM/d/ yo",
  " MM/d/ yy",
  " MM/d/ yyyy",
  " MM/ do/y",
  " MM/ do/ yo",
  " MM/ do/ yy",
  " MM/ do/ yyyy",
  " MM/ dd/y",
  " MM/ dd/ yo",
  " MM/ dd/ yy",
  " MM/ dd/ yyyy",
  " MM/ ddd/y",
  " MM/ ddd/ yo",
  " MM/ ddd/ yy",
  " MM/ ddd/ yyyy",
  " MMM/d/y",
  " MMM/d/ yo",
  " MMM/d/ yy",
  " MMM/d/ yyyy",
  " MMM/ do/y",
  " MMM/ do/ yo",
  " MMM/ do/ yy",
  " MMM/ do/ yyyy",
  " MMM/ dd/y",
  " MMM/ dd/ yo",
  " MMM/ dd/ yy",
  " MMM/ dd/ yyyy",
  " MMM/ ddd/y",
  " MMM/ ddd/ yo",
  " MMM/ ddd/ yy",
  " MMM/ ddd/ yyyy",
  "y/M/d",
  "y/M/ do",
  "y/M/ dd",
  "y/M/ ddd",
  "y/ Mo/d",
  "y/ Mo/ do",
  "y/ Mo/ dd",
  "y/ Mo/ ddd",
  "y/ MM/d",
  "y/ MM/ do",
  "y/ MM/ dd",
  "y/ MM/ ddd",
  "y/ MMM/d",
  "y/ MMM/ do",
  "y/ MMM/ dd",
  "y/ MMM/ ddd",
  " yo/M/d",
  " yo/M/ do",
  " yo/M/ dd",
  " yo/M/ ddd",
  " yo/ Mo/d",
  " yo/ Mo/ do",
  " yo/ Mo/ dd",
  " yo/ Mo/ ddd",
  " yo/ MM/d",
  " yo/ MM/ do",
  " yo/ MM/ dd",
  " yo/ MM/ ddd",
  " yo/ MMM/d",
  " yo/ MMM/ do",
  " yo/ MMM/ dd",
  " yo/ MMM/ ddd",
  " yy/M/d",
  " yy/M/ do",
  " yy/M/ dd",
  " yy/M/ ddd",
  " yy/ Mo/d",
  " yy/ Mo/ do",
  " yy/ Mo/ dd",
  " yy/ Mo/ ddd",
  " yy/ MM/d",
  " yy/ MM/ do",
  " yy/ MM/ dd",
  " yy/ MM/ ddd",
  " yy/ MMM/d",
  " yy/ MMM/ do",
  " yy/ MMM/ dd",
  " yy/ MMM/ ddd",
  " yyyy/M/d",
  " yyyy/M/ do",
  " yyyy/M/ dd",
  " yyyy/M/ ddd",
  " yyyy/ Mo/d",
  " yyyy/ Mo/ do",
  " yyyy/ Mo/ dd",
  " yyyy/ Mo/ ddd",
  " yyyy/ MM/d",
  " yyyy/ MM/ do",
  " yyyy/ MM/ dd",
  " yyyy/ MM/ ddd",
  " yyyy/ MMM/d",
  " yyyy/ MMM/ do",
  " yyyy/ MMM/ dd",
  " yyyy/ MMM/ ddd",
  "y/d/M",
  "y/d/ Mo",
  "y/d/ MM",
  "y/d/ MMM",
  "y/ do/M",
  "y/ do/ Mo",
  "y/ do/ MM",
  "y/ do/ MMM",
  "y/ dd/M",
  "y/ dd/ Mo",
  "y/ dd/ MM",
  "y/ dd/ MMM",
  "y/ ddd/M",
  "y/ ddd/ Mo",
  "y/ ddd/ MM",
  "y/ ddd/ MMM",
  " yo/d/M",
  " yo/d/ Mo",
  " yo/d/ MM",
  " yo/d/ MMM",
  " yo/ do/M",
  " yo/ do/ Mo",
  " yo/ do/ MM",
  " yo/ do/ MMM",
  " yo/ dd/M",
  " yo/ dd/ Mo",
  " yo/ dd/ MM",
  " yo/ dd/ MMM",
  " yo/ ddd/M",
  " yo/ ddd/ Mo",
  " yo/ ddd/ MM",
  " yo/ ddd/ MMM",
  " yy/d/M",
  " yy/d/ Mo",
  " yy/d/ MM",
  " yy/d/ MMM",
  " yy/ do/M",
  " yy/ do/ Mo",
  " yy/ do/ MM",
  " yy/ do/ MMM",
  " yy/ dd/M",
  " yy/ dd/ Mo",
  " yy/ dd/ MM",
  " yy/ dd/ MMM",
  " yy/ ddd/M",
  " yy/ ddd/ Mo",
  " yy/ ddd/ MM",
  " yy/ ddd/ MMM",
  " yyyy/d/M",
  " yyyy/d/ Mo",
  " yyyy/d/ MM",
  " yyyy/d/ MMM",
  " yyyy/ do/M",
  " yyyy/ do/ Mo",
  " yyyy/ do/ MM",
  " yyyy/ do/ MMM",
  " yyyy/ dd/M",
  " yyyy/ dd/ Mo",
  " yyyy/ dd/ MM",
  " yyyy/ dd/ MMM",
  " yyyy/ ddd/M",
  " yyyy/ ddd/ Mo",
  " yyyy/ ddd/ MM",
  " yyyy/ ddd/ MMM",
];
