export const itemTypes = {
  ECONOMICS_CALCULATION_TYPE: "ECONOMICS_CALCULATION_TYPE",
  ECONOMICS_RESULTS_TYPE: "ECONOMICS_RESULTS_TYPE",
  ECONOMICS_HEATMAP: "ECONOMICS_HEATMAP",
  ECONOMICS_PLOTCHARTS: "ECONOMICS_PLOTCHARTS",
  ECONOMICS_TEMPLATECHARTS: "ECONOMICS_TEMPLATECHARTS",
};
