const ItemTypes = {
  ECONOMICS_CALCULATION_TYPE: "ECONOMICS_CALCULATION_TYPE",
  ECONOMICS_RESULTS_TYPE: "ECONOMICS_RESULTS_TYPE",
  ECONOMICS_TABLE_COLUMNDATA: "ECONOMICS_TABLE_COLUMNDATA",
  ECONOMICS_SENSITIVITIES_XAXIS: "ECONOMICS_SENSITIVITIES_XAXIS",
  ECONOMICS_SENSITIVITIES_YAXIS: "ECONOMICS_SENSITIVITIES_YAXIS",
  ECONOMICS_SENSITIVITIES_ZAXIS: "ECONOMICS_SENSITIVITIES_ZAXIS",
  ECONOMICS_SENSITIVITIES: "ECONOMICS_SENSITIVITIES",
};
export default ItemTypes;
