const ItemTypes = {
  ECONOMICS_CALCULATION_TYPE: "ECONOMICS_CALCULATION_TYPE",
  ECONOMICS_RESULTS_TYPE: "ECONOMICS_RESULTS_TYPE",
  ECONOMICS_TABLE_COLUMNDATA: "ECONOMICS_TABLE_COLUMNDATA",
};
export default ItemTypes;
